spring.restclient.uri.product_service=${PRODUCT_SERVICE_URI:http://products-service:8081}
spring.restclient.uri.user_service=${USERS_SERVICE_URI:http://users-service:8082}
spring.restclient.uri.reviews_service=${REVIEWS_SERVICE_URI:http://reviews-service:8083}
spring.restclient.uri.orders_service=${ORDERS_SERVICE_URI:http://order-service:8084}

spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI:http://keycloak:8090/realms/merchly}
spring.security.oauth2.client.provider.keycloak.authorization-uri=${KEYCLOAK_AUTHORIZATION_URI:http://keycloak:8090/realms/merchly/protocol/openid-connect/auth}
spring.security.oauth2.client.provider.keycloak.token-uri=${KEYCLOAK_TOKEN_URI:http://keycloak:8090/realms/merchly/protocol/openid-connect/token}
spring.security.oauth2.client.provider.keycloak.user-info-uri=${KEYCLOAK_USERINFO_URI:http://keycloak:8090/realms/merchly/protocol/openid-connect/userinfo}
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=${KEYCLOAK_JWKSET_URI:http://keycloak:8090/realms/merchly/protocol/openid-connect/certs}
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

minio.url=${MINIO_PUBLIC_URL:http://localhost:9000}
