spring.restclient.uri.product_service=${PRODUCT_SERVICE_URI:http://localhost:8081}
spring.restclient.uri.user_service=${USERS_SERVICE_URI:http://localhost:8082}
spring.restclient.uri.reviews_service=${REVIEWS_SERVICE_URI:http://localhost:8083}
spring.restclient.uri.orders_service=${ORDERS_SERVICE_URI:http://localhost:8084}
spring.restclient.uri.api_gateway=${GATEWAY_SERVICE_URI:http://localhost:8086}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/merchly}

spring.security.oauth2.client.provider.keycloak.token-uri=${KEYCLOAK_TOKEN_URI:http://localhost:8090/realms/merchly/protocol/openid-connect/token}

minio.url=${MINIO_PUBLIC_URL:http://localhost:9000}
