server.port=8080

spring.mvc.hiddenmethod.filter.enabled=true

logging.level.org.springframework.web.client.RestClient=DEBUG

spring.security.oauth2.client.registration.internal-service-client.client-id=merchly_frontend_client
spring.security.oauth2.client.registration.internal-service-client.client-secret=${FRONTEND_SERVICE_CLIENT_SECRET}
spring.security.oauth2.client.registration.internal-service-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.internal-service-client.scope=openid
spring.security.oauth2.client.registration.internal-service-client.provider=keycloak

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
