server.port=8080

spring.mvc.hiddenmethod.filter.enabled=true

logging.level.org.springframework.web.client.RestClient=DEBUG

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
