spring.restclient.uri.product_service=${PRODUCT_SERVICE_URI:http://products-service:8081}
spring.restclient.uri.user_service=${USERS_SERVICE_URI:http://users-service:8082}
spring.restclient.uri.reviews_service=${REVIEWS_SERVICE_URI:http://reviews-service:8083}
spring.restclient.uri.orders_service=${ORDERS_SERVICE_URI:http://order-service:8084}
spring.restclient.uri.api_gateway=${GATEWAY_SERVICE_URI:http://gateway-service:8086}

minio.url=${MINIO_PUBLIC_URL:http://localhost:9000}
