spring.datasource.url=jdbc:postgresql://${ORDERS_DB_HOST:orders_db}:${ORDERS_DB_PORT:5432}/${ORDERS_DB_NAME}
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.initialization-fail-timeout=0
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://keycloak:8090/realms/merchly}
spring.security.oauth2.client.provider.keycloak.token-uri=${KEYCLOAK_TOKEN_URI:http://keycloak:8090/realms/merchly/protocol/openid-connect/token}

spring.restclient.uri.product_service=${PRODUCT_SERVICE_URI:http://products-service:8081}
spring.restclient.uri.user_service=${USERS_SERVICE_URI:http://users-service:8082}
