spring.datasource.url=jdbc:postgresql://${PRODUCTS_DB_HOST:products_db}:${PRODUCTS_DB_PORT:5432}/${PRODUCTS_DB_NAME}
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.initialization-fail-timeout=0
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://keycloak:8090/realms/merchly}
