spring.datasource.url=jdbc:postgresql://${PRODUCTS_DB_HOST:localhost}:${PRODUCTS_DB_PORT:5433}/${PRODUCTS_DB_NAME}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/merchly}
