server.port=8081
spring.cache.type=redis

logging.level.org.springframework.web=DEBUG

spring.datasource.username=${PRODUCTS_DB_USER}
spring.datasource.password=${PRODUCTS_DB_PASSWORD}

minio.url=${MINIO_URL}
minio.access.name=${MINIO_ACCESS_KEY}
minio.access.secret=${MINIO_SECRET_KEY}
minio.bucket.products=merchly-products

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=product-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=io.cvvexxx.products.event.OrderCreatedEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

app.kafka.topics.order-created=order-created
app.kafka.topics.order-failed=order-failed
app.kafka.topics.order-cancelled=order-cancelled
