spring.datasource.url=jdbc:postgresql://${REVIEWS_DB_HOST:localhost}:${REVIEWS_DB_PORT:5435}/${REVIEWS_DB_NAME}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/merchly}
