spring.flyway.repair-on-migrate=true
server.port=8083
spring.cache.type=redis

logging.level.org.springframework.web=DEBUG

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${REVIEWS_DB_USER}
spring.datasource.password=${REVIEWS_DB_PASSWORD}
