spring.datasource.url=jdbc:postgresql://${REVIEWS_DB_HOST:reviews_db}:${REVIEWS_DB_PORT:5432}/${REVIEWS_DB_NAME}
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.initialization-fail-timeout=0
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://keycloak:8090/realms/merchly}
