spring.datasource.url=jdbc:postgresql://${USERS_DB_HOST:localhost}:${USERS_DB_PORT:5432}/${USERS_DB_NAME}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/merchly}
keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8090}
