spring.flyway.repair-on-migrate=true
server.port=8082
spring.cache.type=redis

logging.level.org.springframework.web.client.RestClient=DEBUG
logging.level.org.apache.hc.client5.http=DEBUG

spring.datasource.username=${USERS_DB_USER}
spring.datasource.password=${USERS_DB_PASSWORD}

keycloak.realm=merchly
keycloak.client-id=admin-cli
keycloak.admin-username=${KEYCLOAK_ADMIN_USER:admin}
keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD}

minio.url=${MINIO_URL}
minio.access.name=${MINIO_ACCESS_KEY}
minio.access.secret=${MINIO_SECRET_KEY}
minio.bucket.users=merchly-users

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
